# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.antigen.zsh

# Antigen setup start
antigen use oh-my-zsh

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle unixorn/autoupdate-antigen.zshplugin

antigen theme romkatv/powerlevel10k

antigen apply
# Antigen setup end

# Shell setup start
CASE_SENSITIVE="true"
unsetopt histverify
setopt +o nomatch
# Shell setup end

# Source your custom files
if [ -f ~/.zprofile ]; then
    source ~/.zprofile
else
    touch ~/.zprofile
fi

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
