source ~/.antigen.zsh

# Antigen setup start
antigen use oh-my-zsh

antigen bundle git
antigen bundle dnf
antigen bundle pip
antigen bundle python
antigen bundle sudo
antigen bundle jsontools

antigen theme bhilburn/powerlevel9k

antigen apply
# Antigen setup end

# Theme setup start
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator time)
# Theme setup end

# Shell setup start
CASE_SENSITIVE="true"
unsetopt histverify
# Shell setup end

# Source your custom files
if [ -f ~/.zshprofile ]; then
    source ~/.zshprofile
else
    touch ~/.zshprofile
fi
